
/* Drop Tables */

DROP TABLE SEQUENTIAL_NUMBER_MANAGE;
DROP TABLE USER_ATTRIBUTE;




/* Create Tables */

CREATE TABLE SEQUENTIAL_NUMBER_MANAGE
(
	SEQUENTIAL_CLASS_ID CHAR(4) NOT NULL,
	SEQUENTIAL_VALUE INTEGER NOT NULL,
	DIGITS INTEGER NOT NULL,
	PREFIX VARCHAR(16),
	SUFFIX VARCHAR(16),
	GENERATE_PATTERN VARCHAR(4) NOT NULL,
	REGISTER_TIMESTAMP TIMESTAMP NOT NULL,
	REGISTER_USER_ID VARCHAR(32) NOT NULL,
	UPDATED_TIMESTAMP TIMESTAMP NOT NULL,
	UPDATED_USER_ID VARCHAR(32) NOT NULL,
	VERSION INTEGER NOT NULL,
	PRIMARY KEY (SEQUENTIAL_CLASS_ID)
);


CREATE TABLE USER_ATTRIBUTE
(
	USER_ID VARCHAR(32) NOT NULL,
	ATTRIBUTE XML,
	REGISTER_TIMESTAMP TIMESTAMP NOT NULL,
	REGISTER_USER_ID VARCHAR(32) NOT NULL,
	UPDATED_TIMESTAMP TIMESTAMP NOT NULL,
	UPDATED_USER_ID VARCHAR(32) NOT NULL,
	VERSION INTEGER NOT NULL,
	PRIMARY KEY (USER_ID)
);



