
/* Drop Tables */

DROP TABLE IF EXISTS POSTAL_CODE;
DROP TABLE IF EXISTS SEQUENTIAL_NUMBER_MANAGE;
DROP TABLE IF EXISTS USER_ATTRIBUTE;




/* Create Tables */

CREATE TABLE POSTAL_CODE
(
	ID INT NOT NULL,
	LOCAL_GOVERNMENT_CODE CHAR(5) NOT NULL,
	POSTAL_CODE CHAR(7) NOT NULL,
	KANA_PREFECTURE_NAME TEXT NOT NULL,
	KANA_MUNICIPALITY_NAME TEXT NOT NULL,
	KANA_AREA_NAME TEXT NOT NULL,
	KANJI_PREFECTURE_NAME TEXT NOT NULL,
	KANJI_MUNICIPALITY_NAME TEXT NOT NULL,
	KANJI_AREA_NAME TEXT NOT NULL,
	REGISTER_TIMESTAMP TIMESTAMP NOT NULL,
	REGISTER_USER_ID VARCHAR(32) NOT NULL,
	UPDATED_TIMESTAMP TIMESTAMP NOT NULL,
	UPDATED_USER_ID VARCHAR(32) NOT NULL,
	VERSION INT NOT NULL,
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE SEQUENTIAL_NUMBER_MANAGE
(
	SEQUENTIAL_CLASS_ID CHAR(4) NOT NULL,
	SEQUENTIAL_VALUE INT NOT NULL,
	DIGITS INT NOT NULL,
	PREFIX VARCHAR(16),
	SUFFIX VARCHAR(16),
	GENERATE_PATTERN VARCHAR(4) NOT NULL,
	REGISTER_TIMESTAMP TIMESTAMP NOT NULL,
	REGISTER_USER_ID VARCHAR(32) NOT NULL,
	UPDATED_TIMESTAMP TIMESTAMP NOT NULL,
	UPDATED_USER_ID VARCHAR(32) NOT NULL,
	VERSION INT NOT NULL,
	PRIMARY KEY (SEQUENTIAL_CLASS_ID)
) WITHOUT OIDS;


CREATE TABLE USER_ATTRIBUTE
(
	USER_ID VARCHAR(32) NOT NULL,
	ATTRIBUTE XML,
	REGISTER_TIMESTAMP TIMESTAMP NOT NULL,
	REGISTER_USER_ID VARCHAR(32) NOT NULL,
	UPDATED_TIMESTAMP TIMESTAMP NOT NULL,
	UPDATED_USER_ID VARCHAR(32) NOT NULL,
	VERSION INT NOT NULL,
	PRIMARY KEY (USER_ID)
) WITHOUT OIDS;



/* Comments */

COMMENT ON TABLE POSTAL_CODE IS '郵便番号';
COMMENT ON COLUMN POSTAL_CODE.ID IS 'ID';
COMMENT ON COLUMN POSTAL_CODE.LOCAL_GOVERNMENT_CODE IS '全国地方公共団体コード';
COMMENT ON COLUMN POSTAL_CODE.POSTAL_CODE IS '郵便番号';
COMMENT ON COLUMN POSTAL_CODE.KANA_PREFECTURE_NAME IS '都道府県名(カナ)';
COMMENT ON COLUMN POSTAL_CODE.KANA_MUNICIPALITY_NAME IS '市区町村名(カナ)';
COMMENT ON COLUMN POSTAL_CODE.KANA_AREA_NAME IS '町域名(カナ)';
COMMENT ON COLUMN POSTAL_CODE.KANJI_PREFECTURE_NAME IS '都道府県名(漢字)';
COMMENT ON COLUMN POSTAL_CODE.KANJI_MUNICIPALITY_NAME IS '市区町村名(漢字)';
COMMENT ON COLUMN POSTAL_CODE.KANJI_AREA_NAME IS '町域名(漢字)';
COMMENT ON COLUMN POSTAL_CODE.REGISTER_TIMESTAMP IS '登録日時';
COMMENT ON COLUMN POSTAL_CODE.REGISTER_USER_ID IS '登録ユーザID';
COMMENT ON COLUMN POSTAL_CODE.UPDATED_TIMESTAMP IS '更新日時';
COMMENT ON COLUMN POSTAL_CODE.UPDATED_USER_ID IS '更新ユーザID';
COMMENT ON COLUMN POSTAL_CODE.VERSION IS 'バージョン';
COMMENT ON TABLE SEQUENTIAL_NUMBER_MANAGE IS '連番管理';
COMMENT ON COLUMN SEQUENTIAL_NUMBER_MANAGE.SEQUENTIAL_CLASS_ID IS '連番区分ID';
COMMENT ON COLUMN SEQUENTIAL_NUMBER_MANAGE.SEQUENTIAL_VALUE IS '連番値';
COMMENT ON COLUMN SEQUENTIAL_NUMBER_MANAGE.DIGITS IS '桁数';
COMMENT ON COLUMN SEQUENTIAL_NUMBER_MANAGE.PREFIX IS 'プレフィックス';
COMMENT ON COLUMN SEQUENTIAL_NUMBER_MANAGE.SUFFIX IS 'サフィックス';
COMMENT ON COLUMN SEQUENTIAL_NUMBER_MANAGE.GENERATE_PATTERN IS '生成パターン';
COMMENT ON COLUMN SEQUENTIAL_NUMBER_MANAGE.REGISTER_TIMESTAMP IS '登録日時';
COMMENT ON COLUMN SEQUENTIAL_NUMBER_MANAGE.REGISTER_USER_ID IS '登録ユーザID';
COMMENT ON COLUMN SEQUENTIAL_NUMBER_MANAGE.UPDATED_TIMESTAMP IS '更新日時';
COMMENT ON COLUMN SEQUENTIAL_NUMBER_MANAGE.UPDATED_USER_ID IS '更新ユーザID';
COMMENT ON COLUMN SEQUENTIAL_NUMBER_MANAGE.VERSION IS 'バージョン';
COMMENT ON TABLE USER_ATTRIBUTE IS 'ユーザ属性';
COMMENT ON COLUMN USER_ATTRIBUTE.USER_ID IS 'ユーザID';
COMMENT ON COLUMN USER_ATTRIBUTE.ATTRIBUTE IS '属性';
COMMENT ON COLUMN USER_ATTRIBUTE.REGISTER_TIMESTAMP IS '登録日時';
COMMENT ON COLUMN USER_ATTRIBUTE.REGISTER_USER_ID IS '登録ユーザID';
COMMENT ON COLUMN USER_ATTRIBUTE.UPDATED_TIMESTAMP IS '更新日時';
COMMENT ON COLUMN USER_ATTRIBUTE.UPDATED_USER_ID IS '更新ユーザID';
COMMENT ON COLUMN USER_ATTRIBUTE.VERSION IS 'バージョン';



