
/* Drop Tables */

DROP TABLE IF EXISTS SEQUENTIAL_NUMBER_MANAGE;
DROP TABLE IF EXISTS USER_ATTRIBUTE;




/* Create Tables */

CREATE TABLE SEQUENTIAL_NUMBER_MANAGE
(
	SEQUENTIAL_CLASS_ID CHAR(4) NOT NULL,
	SEQUENTIAL_VALUE INT NOT NULL,
	DIGITS INT NOT NULL,
	PREFIX VARCHAR(16),
	SUFFIX VARCHAR(16),
	GENERATE_PATTERN VARCHAR(4) NOT NULL,
	REGISTER_TIMESTAMP TIMESTAMP NOT NULL,
	REGISTER_USER_ID VARCHAR(32) NOT NULL,
	UPDATED_TIMESTAMP TIMESTAMP NOT NULL,
	UPDATED_USER_ID VARCHAR(32) NOT NULL,
	VERSION INT NOT NULL,
	PRIMARY KEY (SEQUENTIAL_CLASS_ID)
) WITHOUT OIDS;


CREATE TABLE USER_ATTRIBUTE
(
	USER_ID VARCHAR(32) NOT NULL,
	ATTRIBUTE XML,
	REGISTER_TIMESTAMP TIMESTAMP NOT NULL,
	REGISTER_USER_ID VARCHAR(32) NOT NULL,
	UPDATED_TIMESTAMP TIMESTAMP NOT NULL,
	UPDATED_USER_ID VARCHAR(32) NOT NULL,
	VERSION INT NOT NULL,
	PRIMARY KEY (USER_ID)
) WITHOUT OIDS;



/* Comments */

COMMENT ON TABLE SEQUENTIAL_NUMBER_MANAGE IS '連番管理';
COMMENT ON COLUMN SEQUENTIAL_NUMBER_MANAGE.SEQUENTIAL_CLASS_ID IS '連番区分ID';
COMMENT ON COLUMN SEQUENTIAL_NUMBER_MANAGE.SEQUENTIAL_VALUE IS '連番値';
COMMENT ON COLUMN SEQUENTIAL_NUMBER_MANAGE.DIGITS IS '桁数';
COMMENT ON COLUMN SEQUENTIAL_NUMBER_MANAGE.PREFIX IS 'プレフィックス';
COMMENT ON COLUMN SEQUENTIAL_NUMBER_MANAGE.SUFFIX IS 'サフィックス';
COMMENT ON COLUMN SEQUENTIAL_NUMBER_MANAGE.GENERATE_PATTERN IS '生成パターン';
COMMENT ON COLUMN SEQUENTIAL_NUMBER_MANAGE.REGISTER_TIMESTAMP IS '登録日時';
COMMENT ON COLUMN SEQUENTIAL_NUMBER_MANAGE.REGISTER_USER_ID IS '登録ユーザID';
COMMENT ON COLUMN SEQUENTIAL_NUMBER_MANAGE.UPDATED_TIMESTAMP IS '更新日時';
COMMENT ON COLUMN SEQUENTIAL_NUMBER_MANAGE.UPDATED_USER_ID IS '更新ユーザID';
COMMENT ON COLUMN SEQUENTIAL_NUMBER_MANAGE.VERSION IS 'バージョン';
COMMENT ON TABLE USER_ATTRIBUTE IS 'ユーザ属性';
COMMENT ON COLUMN USER_ATTRIBUTE.USER_ID IS 'ユーザID';
COMMENT ON COLUMN USER_ATTRIBUTE.ATTRIBUTE IS '属性';
COMMENT ON COLUMN USER_ATTRIBUTE.REGISTER_TIMESTAMP IS '登録日時';
COMMENT ON COLUMN USER_ATTRIBUTE.REGISTER_USER_ID IS '登録ユーザID';
COMMENT ON COLUMN USER_ATTRIBUTE.UPDATED_TIMESTAMP IS '更新日時';
COMMENT ON COLUMN USER_ATTRIBUTE.UPDATED_USER_ID IS '更新ユーザID';
COMMENT ON COLUMN USER_ATTRIBUTE.VERSION IS 'バージョン';



