
/* Drop Tables */

DROP TABLE IF EXISTS AUTHORITIES;
DROP TABLE IF EXISTS OAUTH_ACCESS_TOKEN;
DROP TABLE IF EXISTS OAUTH_CLIENT_DETAILS;
DROP TABLE IF EXISTS OAUTH_REFRESH_TOKEN;
DROP TABLE IF EXISTS USERS;




/* Create Tables */

CREATE TABLE AUTHORITIES
(
	USER_ID VARCHAR(32) NOT NULL,
	AUTHORITY VARCHAR(50) NOT NULL,
	REGISTER_TIMESTAMP TIMESTAMP NOT NULL,
	REGISTER_USER_ID VARCHAR(32) NOT NULL,
	UPDATED_TIMESTAMP TIMESTAMP NOT NULL,
	UPDATED_USER_ID VARCHAR(32) NOT NULL,
	VERSION INT NOT NULL,
	PRIMARY KEY (USER_ID, AUTHORITY)
) WITHOUT OIDS;


CREATE TABLE OAUTH_ACCESS_TOKEN
(
	TOKEN_ID TEXT NOT NULL,
	TOKEN BYTEA NOT NULL,
	AUTHENTICATION_ID TEXT NOT NULL,
	USER_NAME TEXT,
	CLIENT_ID TEXT NOT NULL,
	AUTHENTICATION BYTEA NOT NULL,
	REFRESH_TOKEN TEXT,
	PRIMARY KEY (TOKEN_ID)
) WITHOUT OIDS;


CREATE TABLE OAUTH_CLIENT_DETAILS
(
	CLIENT_ID TEXT NOT NULL,
	CLIENT_SECRET CHAR(80) NOT NULL,
	RESOURCE_IDS TEXT,
	SCOPE TEXT NOT NULL,
	AUTHORIZED_GRANT_TYPES TEXT NOT NULL,
	WEB_SERVER_REDIRECT_URI TEXT,
	AUTHORITIES TEXT NOT NULL,
	-- 単位：秒
	ACCESS_TOKEN_VALIDITY INT,
	-- 単位：秒
	REFRESH_TOKEN_VALIDITY INT,
	ADDITIONAL_INFORMATION TEXT,
	PRIMARY KEY (CLIENT_ID)
) WITHOUT OIDS;


CREATE TABLE OAUTH_REFRESH_TOKEN
(
	TOKEN_ID TEXT NOT NULL,
	TOKEN BYTEA NOT NULL,
	AUTHENTICATION BYTEA NOT NULL,
	PRIMARY KEY (TOKEN_ID)
) WITHOUT OIDS;


CREATE TABLE USERS
(
	USER_ID VARCHAR(32) NOT NULL,
	USERNAME VARCHAR(32) NOT NULL,
	PASSWORD CHAR(80) NOT NULL,
	PASSWORD_UPDATED_TIMESTAMP TIMESTAMP NOT NULL,
	ENABLED BOOLEAN NOT NULL,
	INTERIM_REGISTER BOOLEAN NOT NULL,
	LOGIN_ERROR_COUNT INT NOT NULL,
	LOCKOUT_TIMESTAMP TIMESTAMP,
	LAST_LOGIN_TIMESTAMP TIMESTAMP,
	LOGOUT_TIMESTAMP TIMESTAMP,
	REGISTER_TIMESTAMP TIMESTAMP NOT NULL,
	REGISTER_USER_ID VARCHAR(32) NOT NULL,
	UPDATED_TIMESTAMP TIMESTAMP NOT NULL,
	UPDATED_USER_ID VARCHAR(32) NOT NULL,
	VERSION INT NOT NULL,
	PRIMARY KEY (USER_ID)
) WITHOUT OIDS;



/* Create Foreign Keys */

ALTER TABLE AUTHORITIES
	ADD FOREIGN KEY (USER_ID)
	REFERENCES USERS (USER_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;



/* Comments */

COMMENT ON TABLE AUTHORITIES IS '権限';
COMMENT ON COLUMN AUTHORITIES.USER_ID IS 'ユーザID';
COMMENT ON COLUMN AUTHORITIES.AUTHORITY IS '権限';
COMMENT ON COLUMN AUTHORITIES.REGISTER_TIMESTAMP IS '登録日時';
COMMENT ON COLUMN AUTHORITIES.REGISTER_USER_ID IS '登録ユーザID';
COMMENT ON COLUMN AUTHORITIES.UPDATED_TIMESTAMP IS '更新日時';
COMMENT ON COLUMN AUTHORITIES.UPDATED_USER_ID IS '更新ユーザID';
COMMENT ON COLUMN AUTHORITIES.VERSION IS 'バージョン';
COMMENT ON TABLE OAUTH_ACCESS_TOKEN IS 'アクセストークン';
COMMENT ON COLUMN OAUTH_ACCESS_TOKEN.TOKEN_ID IS 'トークンID';
COMMENT ON COLUMN OAUTH_ACCESS_TOKEN.TOKEN IS 'トークンデータ';
COMMENT ON COLUMN OAUTH_ACCESS_TOKEN.AUTHENTICATION_ID IS '認証ID';
COMMENT ON COLUMN OAUTH_ACCESS_TOKEN.USER_NAME IS 'ユーザ名';
COMMENT ON COLUMN OAUTH_ACCESS_TOKEN.CLIENT_ID IS 'クライアントID';
COMMENT ON COLUMN OAUTH_ACCESS_TOKEN.AUTHENTICATION IS '認証データ';
COMMENT ON COLUMN OAUTH_ACCESS_TOKEN.REFRESH_TOKEN IS 'リフレッシュトークン';
COMMENT ON TABLE OAUTH_CLIENT_DETAILS IS 'サービスクライアント';
COMMENT ON COLUMN OAUTH_CLIENT_DETAILS.CLIENT_ID IS 'クライアントID';
COMMENT ON COLUMN OAUTH_CLIENT_DETAILS.CLIENT_SECRET IS 'クライアントシークラット';
COMMENT ON COLUMN OAUTH_CLIENT_DETAILS.RESOURCE_IDS IS 'リソースID';
COMMENT ON COLUMN OAUTH_CLIENT_DETAILS.SCOPE IS 'スコープ';
COMMENT ON COLUMN OAUTH_CLIENT_DETAILS.AUTHORIZED_GRANT_TYPES IS '認可グラントタイプ';
COMMENT ON COLUMN OAUTH_CLIENT_DETAILS.WEB_SERVER_REDIRECT_URI IS 'WEBサーバリダイレクトURL';
COMMENT ON COLUMN OAUTH_CLIENT_DETAILS.AUTHORITIES IS '権限';
COMMENT ON COLUMN OAUTH_CLIENT_DETAILS.ACCESS_TOKEN_VALIDITY IS 'アクセストークン有効期間';
COMMENT ON COLUMN OAUTH_CLIENT_DETAILS.REFRESH_TOKEN_VALIDITY IS 'リフレッシュトーク有効期間';
COMMENT ON COLUMN OAUTH_CLIENT_DETAILS.ADDITIONAL_INFORMATION IS '追加情報';
COMMENT ON TABLE OAUTH_REFRESH_TOKEN IS 'リフレッシュトークン';
COMMENT ON COLUMN OAUTH_REFRESH_TOKEN.TOKEN_ID IS 'トークンID';
COMMENT ON COLUMN OAUTH_REFRESH_TOKEN.TOKEN IS 'トークンデータ';
COMMENT ON COLUMN OAUTH_REFRESH_TOKEN.AUTHENTICATION IS '認証データ';
COMMENT ON TABLE USERS IS 'ユーザ';
COMMENT ON COLUMN USERS.USER_ID IS 'ユーザID';
COMMENT ON COLUMN USERS.USERNAME IS 'ユーザ名';
COMMENT ON COLUMN USERS.PASSWORD IS 'パスワード';
COMMENT ON COLUMN USERS.PASSWORD_UPDATED_TIMESTAMP IS 'パスワード更新日時';
COMMENT ON COLUMN USERS.ENABLED IS '有効フラグ';
COMMENT ON COLUMN USERS.INTERIM_REGISTER IS '仮登録フラグ';
COMMENT ON COLUMN USERS.LOGIN_ERROR_COUNT IS 'ログインエラー回数';
COMMENT ON COLUMN USERS.LOCKOUT_TIMESTAMP IS 'ロックアウト日時';
COMMENT ON COLUMN USERS.LAST_LOGIN_TIMESTAMP IS '最終ログイン日時';
COMMENT ON COLUMN USERS.LOGOUT_TIMESTAMP IS 'ログアウト日時';
COMMENT ON COLUMN USERS.REGISTER_TIMESTAMP IS '登録日時';
COMMENT ON COLUMN USERS.REGISTER_USER_ID IS '登録ユーザID';
COMMENT ON COLUMN USERS.UPDATED_TIMESTAMP IS '更新日時';
COMMENT ON COLUMN USERS.UPDATED_USER_ID IS '更新ユーザID';
COMMENT ON COLUMN USERS.VERSION IS 'バージョン';



