
/* Drop Tables */

DROP TABLE AUTHORITIES;
DROP TABLE USERS;




/* Create Tables */

CREATE TABLE AUTHORITIES
(
	USER_ID VARCHAR(32) NOT NULL,
	AUTHORITY VARCHAR(50) NOT NULL,
	REGISTER_TIMESTAMP TIMESTAMP NOT NULL,
	REGISTER_USER_ID VARCHAR(32) NOT NULL,
	UPDATED_TIMESTAMP TIMESTAMP NOT NULL,
	UPDATED_USER_ID VARCHAR(32) NOT NULL,
	VERSION INTEGER NOT NULL,
	PRIMARY KEY (USER_ID, AUTHORITY)
);


CREATE TABLE USERS
(
	USER_ID VARCHAR(32) NOT NULL,
	USERNAME VARCHAR(32) NOT NULL,
	PASSWORD CHAR(80) NOT NULL,
	PASSWORD_UPDATED_TIMESTAMP TIMESTAMP NOT NULL,
	ENABLED BOOLEAN NOT NULL,
	INTERIM_REGISTER BOOLEAN NOT NULL,
	LOGIN_ERROR_COUNT INTEGER NOT NULL,
	LOCKOUT_TIMESTAMP TIMESTAMP,
	LAST_LOGIN_TIMESTAMP TIMESTAMP,
	LOGOUT_TIMESTAMP TIMESTAMP,
	REGISTER_TIMESTAMP TIMESTAMP NOT NULL,
	REGISTER_USER_ID VARCHAR(32) NOT NULL,
	UPDATED_TIMESTAMP TIMESTAMP NOT NULL,
	UPDATED_USER_ID VARCHAR(32) NOT NULL,
	VERSION INTEGER NOT NULL,
	PRIMARY KEY (USER_ID)
);



/* Create Foreign Keys */

ALTER TABLE AUTHORITIES
	ADD FOREIGN KEY (USER_ID)
	REFERENCES USERS (USER_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;



