DROP TABLE T_ADDRESS;

CREATE TABLE T_ADDRESS (
  ID INTEGER PRIMARY KEY,
  MAIL_ADDRESS VARCHAR(128) NOT NULL,
  ADDRESS_NAME VARCHAR(128),
  SMTP_SERVER_NAME VARCHAR(32) NOT NULL,
  SMTP_PORT INTEGER,
  AUTH_USER_NAME VARCHAR(32),
  AUTH_PASSWORD VARCHAR(32),
  EXCLUSIVE_KEY INTEGER NOT NULL
);
