DROP TABLE T_USER_INFO;

CREATE TABLE T_USER_INFO (
  USER_ID CHAR(16) PRIMARY KEY,
  USER_NAME CHAR(64) NOT NULL,
  PASSWORD CHAR(64) NOT NULL,
  AUTH_CD CHAR(1) NOT NULL,
  REGISTER_DATETIME CHAR(14) NOT NULL,
  REGISTER_USER_ID CHAR(16) NOT NULL,
  UPDATED_DATETIME CHAR(14) NOT NULL,
  UPDATED_USER_ID CHAR(16) NOT NULL,
  EXCLUSIVE_KEY INTEGER NOT NULL
);
