CREATE TABLE USERS (
  USER_ID VARCHAR(16) PRIMARY KEY,
  USERNAME VARCHAR(16) NOT NULL,
  PASSWORD VARCHAR(64) NOT NULL,
  ENABLED BOOLEAN NOT NULL,
  REGISTER_DATETIME CHAR(14) NOT NULL,
  REGISTER_USER_ID VARCHAR(16) NOT NULL,
  UPDATED_DATETIME CHAR(14) NOT NULL,
  UPDATED_USER_ID VARCHAR(16) NOT NULL,
  VERSION INTEGER NOT NULL
);

CREATE TABLE AUTHORITIES (
  USER_ID VARCHAR(16) NOT NULL,
  AUTHORITY VARCHAR(50) NOT NULL,
  REGISTER_DATETIME CHAR(14) NOT NULL,
  REGISTER_USER_ID VARCHAR(16) NOT NULL,
  UPDATED_DATETIME CHAR(14) NOT NULL,
  UPDATED_USER_ID VARCHAR(16) NOT NULL,
  VERSION INTEGER NOT NULL,
  PRIMARY KEY (USER_ID, AUTHORITY),
  CONSTRAINT FK_AUTHORITIES_USERS FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID)
);
